apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sopSeed.name" . }}-acct
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sopSeed.labels" . | nindent 4 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name | lower }}"
  labels:
    {{- include "sopSeed.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      name: "{{ .Release.Name | lower }}"
      labels:
        app.kubernetes.io/name: {{ include "sopSeed.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name | lower }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      serviceAccountName: {{ include "sopSeed.name" . }}-acct
      restartPolicy: Never
      {{- if .Values.initContainers.enabled }}
      initContainers:
        - name: {{ .Chart.Name }}-init
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh"]
          args:
            - "-c"
            - |
              # Modern container runtimes should provide sufficient entropy
              # Just verify it's available
              if [ $(cat /proc/sys/kernel/random/entropy_avail) -lt 256 ]; then
                echo "Insufficient entropy available. Please check your container runtime configuration."
                exit 1
              fi
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: GNUPGHOME
              value: "{{ .Values.global.userHome }}/.gnupg"
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
          command: ["/bin/sh", "{{ .Values.global.userHome }}/sopSeed.sh"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: user-home
              mountPath: {{ .Values.global.userHome }}
              readOnly: false
            - name: crypto-script
              mountPath: {{ .Values.global.userHome }}/sopSeed.sh
              subPath: sopSeed.sh
              readOnly: true
            {{- if not .Values.age.enabled }}
            - name: gpg-conf
              mountPath: {{ .Values.global.userHome }}/gpg.conf
              subPath: gpg.conf
              readOnly: true
            - name: gpg-batch
              mountPath: {{ .Values.global.userHome }}/gpg.batch
              subPath: gpg.batch
              readOnly: true
            {{- end }}
      volumes:
        - name: user-home
          emptyDir: {}
        {{- if .Values.initContainers.enabled }}
        - name: entropy-script
          configMap:
            name: {{ include "sopSeed.name" . }}-entropy-script
            defaultMode: 0755
        {{- end }}
        - name: crypto-script
          configMap:
            name: {{ include "sopSeed.name" . }}-crypto-script
            defaultMode: 0755
        {{- if not .Values.age.enabled }}
        - name: gpg-conf
          configMap:
            name: {{ include "sopSeed.name" . }}-gpg-conf
            defaultMode: 0640
        - name: gpg-batch
          configMap:
            name: {{ include "sopSeed.name" . }}-gpg-batch
            defaultMode: 0640
        {{- end }}
