{{- if .Release.IsInstall -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "gitfence.name" . }}-acct
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitfence.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "gitfence.name" . }}-acct
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitfence.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "gitfence.name" . }}-acct
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "gitfence.name" . }}-acct
  apiGroup: rbac.authorization.k8s.io
{{- end }}