name: Cleanup Old Actions Runs

on:
  schedule:
    - cron: "0 0 1 * *" # Run monthly on the 1st
  workflow_dispatch: # Allow manual runs

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write # Required to delete workflow runs
      contents: read # Required to read repository

    steps:
      - name: Run cleanup script
        run: |
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          REPO="${{ github.repository }}"
          RETENTION_DAYS=90

          echo "Fetching all workflow runs..."
          PAGE=1
          ALL_RUNS=()

          while true; do
            RESPONSE=$(curl -s -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: token ${TOKEN}" \
              "https://api.github.com/repos/${REPO}/actions/runs?per_page=100&page=${PAGE}")

            RUNS=$(echo "${RESPONSE}" | jq -r '.workflow_runs[]')
            if [ -z "${RUNS}" ]; then
              break
            fi

            ALL_RUNS+=("${RUNS}")
            PAGE=$((PAGE + 1))
          done

          if [ ${#ALL_RUNS[@]} -eq 0 ]; then
            echo "No workflow runs found"
            exit 0
          fi

          # Calculate cutoff date (90 days ago)
          CUTOFF=$(date -d "${RETENTION_DAYS} days ago" +%s)

          echo "Processing runs from all workflows..."
          TO_DELETE=$(echo "${ALL_RUNS[@]}" | jq -r --arg CUTOFF "$CUTOFF" \
            'select(.created_at | fromdateiso8601 < ($CUTOFF | tonumber)) | .id')

          if [ -z "$TO_DELETE" ]; then
            echo "No runs older than ${RETENTION_DAYS} days found"
            exit 0
          fi

          echo "Found $(echo "$TO_DELETE" | wc -l) runs to delete..."
          echo "Will delete all runs older than ${RETENTION_DAYS} days..."

          for RUN_ID in ${TO_DELETE}; do
            echo "Deleting run ${RUN_ID}..."
            RESPONSE=$(curl -X DELETE -s -o /dev/null -w "%{http_code}" \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: token ${TOKEN}" \
              "https://api.github.com/repos/${REPO}/actions/runs/${RUN_ID}")

            if [ "$RESPONSE" = "204" ] || [ "$RESPONSE" = "200" ]; then
              echo "Successfully deleted run ${RUN_ID}"
            else
              echo "Failed to delete run ${RUN_ID} (HTTP ${RESPONSE})"
            fi
          done
