name: Test and Release sopSeed Helm Chart

on:
  push:
    paths:
      - "./chart/**"
  pull_request:
    paths:
      - "./chart/**"
      - ".github/workflows/helm-release.yml"
  workflow_dispatch:

permissions:
  contents: read

env:
  HELM_VERSION: v3.13.3

jobs:
  lint-test:
    name: Lint and Test sopSeed Helm Chart
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: ${{ env.HELM_VERSION }}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.0"

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1
        with:
          version: v3.9.0
          yamllint_version: 1.32.0
          yamale_version: 4.0.4

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          # Determine the target branch
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            TARGET_BRANCH="${{ github.base_ref }}"
            # Fetch the target branch
            git fetch origin ${TARGET_BRANCH}:${TARGET_BRANCH}
          else
            TARGET_BRANCH="main"
          fi

          echo "Running chart-testing against target branch: ${TARGET_BRANCH}"

          changed=$(ct list-changed --target-branch ${TARGET_BRANCH})
          if [[ ! -n "${changed}" ]]; then
            echo "CHANGED=true" >> $GITHUB_ENV
          fi

      - name: Run chart-testing (lint)
        if: ${{ env.CHANGED == 'true' }}
        run: |
          ct lint --config chart/ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.12.0
        if: ${{ env.CHANGED == 'true' }}

      - name: Run chart-testing (install)
        if: ${{ env.CHANGED == 'true' }}
        run: |
          ct install --config chart/ct.yaml

  release:
    name: Release sopSeed Helm Chart
    needs: lint-test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    if: ${{ github.event_name != 'pull_request' }}
    outputs:
      chart_version: ${{ steps.set_version.outputs.chart_version }}
      base64_hash: ${{ steps.hash.outputs.base64_hash }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@gmail.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Package Helm Chart
        id: set_version
        env:
          CHART_DIR: "./chart"
        run: |
          cd ${CHART_DIR}
          helm dependency build
          CHART_VERSION=$(helm show chart . | grep '^version:' | cut -d' ' -f2)
          echo "chart_version=$CHART_VERSION" >> $GITHUB_OUTPUT
          cd -
          helm package ${CHART_DIR} -d .helm-charts

      - name: Compute chart hash (base64)
        id: hash
        run: |
          sha256sum .helm-charts/sopseed-${{ steps.set_version.outputs.chart_version }}.tgz > .helm-charts/sopseed-${{ steps.set_version.outputs.chart_version }}.sha256
          base64 .helm-charts/sopseed-${{ steps.set_version.outputs.chart_version }}.sha256 > .helm-charts/sopseed-${{ steps.set_version.outputs.chart_version }}.sha256.b64
          echo "base64_hash=$(cat .helm-charts/sopseed-${{ steps.set_version.outputs.chart_version }}.sha256.b64)" >> $GITHUB_OUTPUT

      - name: Push Helm Chart to OCI Registry
        env:
          HELM_EXPERIMENTAL_OCI: 1
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin
          helm push .helm-charts/sopseed-${{ steps.set_version.outputs.chart_version }}.tgz oci://ghcr.io/${{ github.repository_owner }}/sopseed-chart

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release v${{ steps.set_version.outputs.chart_version }}
          tag_name: v${{ steps.set_version.outputs.chart_version }}
          draft: false
          prerelease: false
          files: .helm-charts/sopseed-${{ steps.set_version.outputs.chart_version }}.tgz
          fail_on_unmatched_files: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  provenance:
    name: Generate SLSA Provenance for Helm Chart
    needs: release
    runs-on: ubuntu-latest
    permissions:
      actions: read
      id-token: write
      contents: write
    if: startsWith(github.ref, 'refs/tags/')
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.1.0
    with:
      base64-subjects: ${{ needs.release.outputs.base64_hash }}
      upload-assets: true
      upload-tag-name: v${{ needs.release.outputs.chart_version }}
