name: Maintenance

on:
  schedule:
    - cron: "0 0 1 * *"  # Monthly cleanup
  workflow_dispatch:
    inputs:
      run_package_cleanup:
        description: "Run package cleanup"
        type: boolean
        default: true
      run_actions_cleanup:
        description: "Run actions cleanup"
        type: boolean
        default: true
      packages:
        description: "Packages to clean (comma-separated, overrides DEFAULT_PACKAGES)"
        type: string
        required: false
      keep_versions:
        description: "Number of package versions to keep"
        type: number
        default: 3
        required: false
      artifact_type:
        description: "Type of artifact to clean"
        type: choice
        options:
          - container
          - helm
        default: "container"
        required: false
      retention_days:
        description: "Days to retain action runs"
        type: number
        default: 90
        required: false
      workflows:
        description: 'Workflows to clean (comma-separated or "all")'
        type: string
        default: "all"
        required: false

jobs:
  package-cleanup:
    if: inputs.run_package_cleanup || github.event_name == 'schedule'
    uses: ossfellow/.github/.github/workflows/package-maintenance.yml@main
    with:
      packages: ${{ inputs.packages || 'sopseed,sopseed-chart' }}
      keep_versions: ${{ inputs.keep_versions || 3 }}
      artifact_type: ${{ inputs.artifact_type || 'container' }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  actions-cleanup:
    if: inputs.run_actions_cleanup || github.event_name == 'schedule'
    uses: ossfellow/.github/.github/workflows/actions-maintenance.yml@main
    with:
      retention_days: ${{ inputs.retention_days || 90 }}
      workflows: ${{ inputs.workflows || 'all' }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
