name: Maintenance

on:
  schedule:
    - cron: "0 0 1 * *"  # Monthly cleanup
  workflow_dispatch:
    inputs:
      run_package_cleanup:
        description: "Run package cleanup"
        type: boolean
        default: true
      run_actions_cleanup:
        description: "Run actions cleanup"
        type: boolean
        default: true
      packages:
        description: "Packages to clean (comma-separated, overrides DEFAULT_PACKAGES)"
        type: string
        required: false
      keep_versions:
        description: "Number of package versions to keep"
        type: number
        default: 3
        required: false
      artifact_type:
        description: "Type of artifact to clean"
        type: choice
        options:
          - container
          - helm
        default: "container"
        required: false
      retention_days:
        description: "Days to retain action runs"
        type: number
        default: 90
        required: false
      workflows:
        description: 'Workflows to clean (comma-separated or "all")'
        type: string
        default: "all"
        required: false

jobs:
  package-cleanup:
    if: inputs.run_package_cleanup || github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: Delete old package versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ inputs.packages || 'sopseed,sopseed-chart' }}
          package-type: ${{ inputs.artifact_type || 'container' }}
          min-versions-to-keep: ${{ inputs.keep_versions || 3 }}
          token: ${{ secrets.GITHUB_TOKEN }}

  actions-cleanup:
    if: inputs.run_actions_cleanup || github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: ${{ inputs.retention_days || 90 }}
          keep_minimum_runs: 1
          delete_workflow_by_state_pattern: "All"
          delete_workflow_pattern: ${{ inputs.workflows || 'all' }}
